{
  parserClass="parsing.CMakeParser"
 
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
 
  psiClassPrefix="CMake"
  psiImplClassSuffix="Impl"
  psiPackage="psi"
  psiImplPackage="psi.impl"
 
  elementTypeHolderClass="psi.CMakeTypes"
  elementTypeClass="psi.CMakeElementType"
  tokenTypeClass="psi.CMakeTokenType"
 }
 
 file         ::=  file_element*
 file_element ::=  command_invocation line_ending | (bracket_comment|space)* line_ending
 line_ending  ::=  line_comment? newline
 space        ::=  '[ \t]+'
 newline      ::=  '\n'
 
 command_invocation  ::=  space* identifier space* '(' arguments ')'
 identifier          ::=  '[A-Za-z][A-Za-z0-9_]*'
 arguments           ::=  argument? separated_arguments*
 separated_arguments ::=  separation+ argument? |
                          separation* '(' arguments ')'
 separation          ::=  space | line_ending
 
 argument ::=  bracket_argument | quoted_argument | unquoted_argument
 
 bracket_argument ::=  bracket_open bracket_content bracket_close
 bracket_open     ::=  '[' '='+ '['
 bracket_content  ::=  '.*'
 bracket_close    ::=  ']' '='+ ']'
 
 quoted_argument     ::=  '"' quoted_element* '"'
 quoted_element      ::=  '[^\\\"]' | escape_sequence | quoted_continuation
 quoted_continuation ::=  '\' newline
 
 unquoted_argument ::=  unquoted_element+
 unquoted_element  ::=  '[^ \(\)\#\"\\]' | escape_sequence
 
 escape_sequence  ::=  escape_identity | escape_encoded | escape_semicolon
 escape_identity  ::=  '\(' | '\)' | '\#' | '\"' | '\ ' |
                       '\\' | '\$' | '\@' | '\^'
 escape_encoded   ::=  '\t' | '\r' | '\n'
 escape_semicolon ::=  '\;'
 
 bracket_comment ::=  '#' bracket_argument
 
 line_comment ::=  '#'
 
 var_ref ::= '${' identifier '}'